# Notebook to subset final watersheds

Cascade Tuholske cascade@ucsb.edu <br>

In [5]:
#### Dependencies

import pandas as pd
import numpy as np
import geopandas as gpd

In [6]:
#### File Names and DIR
DATA_IN = '/home/cascade/projects/wastewater/data/'
PP_N_ALL_FN = 'processed/N_effluent_output/effluent_N_pourpoints_all.shp'
PP_N_ALL = gpd.read_file(DATA_IN+PP_N_ALL_FN)
FIO_WATERSHED_FN = 'processed/FIO_effluent_output/effluent_FIO_watersheds.shp'
FIO_WATERSHED = gpd.read_file(DATA_IN+FIO_WATERSHED_FN)

In [10]:
PP_N_ALL.sort_values(by = 'tot_N', ascending = False).head(100)

,basin_id,open_N,septic_N,treated_N,tot_N,open_N_pct,septic_N_p,treated_N_,tot_pct,geometry
117407,al_12731,4.530756e+11,8.159916e+09,2.400176e+11,7.012526e+11,64.609467,1.163620,34.226979,100.000066,POINT (10886623.22152479 3870490.275355731)
116362,al_13237,3.522885e+11,1.874379e+10,7.989864e+09,3.790222e+11,92.946666,4.945302,2.108020,99.999988,POINT (8649617.041968619 2787936.463795102)
116358,al_13478,1.299023e+11,2.540993e+09,6.107524e+10,1.935184e+11,67.126556,1.313050,31.560428,100.000034,POINT (10836904.34066086 2718886.850084023)
132694,af_16862,8.085761e+10,6.236841e+09,3.885397e+10,1.259483e+11,64.199053,4.951906,30.849145,100.000104,POINT (2750821.628472521 3794658.939889039)
117895,al_11370,7.612309e+10,1.371452e+09,4.428319e+10,1.217778e+11,62.509848,1.126193,36.363945,99.999985,POINT (10325097.87759038 4538233.881555353)
...,...,...,...,...,...,...,...,...,...,...
117363,al_11682,4.097225e+09,7.369575e+07,2.291870e+09,6.462790e+09,63.397152,1.140309,35.462545,100.000005,POINT (11161911.10271569 3640130.021828748)
127420,af_15456,5.986480e+09,6.082791e+07,3.552616e+08,6.402569e+09,93.501216,0.950055,5.548735,100.000006,POINT (339931.1468320903 792829.1121334088)
116030,al_13384,4.327692e+09,7.794847e+07,1.979887e+09,6.385527e+09,67.773453,1.220705,31.005848,100.000005,POINT (10450424.76934933 2646762.443315563)
10861,eu_26322,1.135279e+09,8.563442e+08,4.231528e+09,6.223151e+09,18.242835,13.760620,67.996542,99.999998,POINT (1055668.20661958 6245087.479544288)
11610,eu_25190,9.276519e+08,1.205264e+08,5.154099e+09,6.202278e+09,14.956633,1.943260,83.100096,99.999988,POINT (1496338.862559299 6420555.87284423)

In [3]:
#### Subset Top 100 for FIO & Match to PP Location
treat_type = 'effluent'
fn_out = 'processed/FIO_effluent_output/effluent_FIO_pourpoints_100.shp'
data_out = FIO_WATERSHED.sort_values(by = treat_type, ascending = False).head(100)
data_out = data_out[['basin_id','effluent']]
data_out.rename(columns={'effluent':'FIO_effluent'}, inplace=True)
data_out = gpd.GeoDataFrame(pd.merge(data_out, PP_N_ALL[['basin_id', 'geometry']], on = 'basin_id', how = 'inner'))
data_out['rank'] = list(range(1,101))
data_out.to_file(DATA_IN+fn_out)

In [4]:
#### Subset Top 100 N by Type
treat_types = ['tot_N', 'septic_N', 'open_N', 'treated_N']

for treat_type in treat_types:

    fn_out = 'processed/N_effluent_output/effluent_N_pourpoints_'+treat_type+'100.shp'
    data_out = PP_N_ALL.sort_values(by = treat_type, ascending = False).head(100)
    data_out = data_out[['basin_id', 'geometry', treat_type]]
    data_out['rank'] = list(range(1,101))

    data_out.to_file(DATA_IN+fn_out)